GROUP_REPOS = [
    {
        "name": "JOMS",
        "gitLinks": ["https://github.com/JOMS-inc/JOMSearch.git"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "visionJAMx",
        "gitLinks": ["https://github.com/visionJAMx/whoknows"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    }, 
    { 
        "name": "WeKnowXD",
        "gitLinks": ["https://github.com/WeKnowXD/WeKnowXD_Project"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    }, 

    {
        "name": "MaxiKnows",
        "gitLinks": ["https://github.com/maxiknows/maxi-knows.git"],
        "backend": "http://68.221.17.27:8080/",
        "frontend": "http://68.221.17.27:8080/",
        "monitoring": "",
        "stack": ["Go", "Go Standard Library", "SQLite"],
        "documentation": [],
        "sla": "",
    },
    
    {
    "name": "JakobMagnusBardie",
    "gitLinks": ["https://github.com/JacobMagnusBardie/WhoKnowsWho"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
    {
        "name": "GenZM0nks",
        "gitLinks": ["https://github.com/GenZM0nks/AscendingMonk"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Group Group",
        "gitLinks": ["https://github.com/Gruppegruppe/SearchEngine"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
    "name": "devops-gruppe-2",
    "gitLinks": ["https://github.com/devops-gruppe-2/search-engine"],
    "backend": "",
    "frontend": "",
    "monitoring": "",
    "stack": [],
    "documentation": [],
    "sla": "",
},
]
